spring.datasource.url=jdbc:postgresql://localhost:5432/lead_exchange
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.cloud.openfeign.client.config.topnlab.url=https://agencies-p.topnlab.ru
spring.cloud.openfeign.client.config.analyticsplus.url=https://api.analyticsplus.tech
external.api.token=${EXTERNAL_API_TOKEN:default-token}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.forward-headers-strategy=framework
spring.flyway.clean-disabled=false

resilience4j.ratelimiter.instances.topnlabApieRateLimiter.limit-for-period=6
resilience4j.ratelimiter.instances.topnlabApieRateLimiter.limit-refresh-period=1
resilience4j.ratelimiter.instances.topnlabApieRateLimiter.timeout-duration=6
telegram.bot.token=${BOT_TOKEN:default-token}

tma.auth.enabled=true
tma.auth.max-age-seconds=300
tma.auth.public-paths=/swagger-ui,/v3/api-docs

enable.local.dev=true
