spring.datasource.url=jdbc:postgresql://localhost:5432/lead_exchange
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.forward-headers-strategy=framework

telegram.bot.token=7917590681:AAHzssSftBfY3ctBw6NzB9PiUpXN3wv0r-w
