spring.datasource.url=jdbc:postgresql://localhost:5432/lead_exchange
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.forward-headers-strategy=framework
spring.flyway.clean-disabled=false

external.api.token=${EXTERNAL_API_TOKEN}
external.api.url-ids=https://api.analyticsplus.tech/users/api/realty/by-phone
external.api.url-entity=https://agencies-p.topnlab.ru/public/get-entities
