name: Sync estates daily

on:
  schedule:
    - cron: "0 3 * * *"   # каждый день в 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Call API for syncing estates
        run: |
          curl -X POST \
          https://lead-exchange/api/external/sync-all
